log_dir: "logs/20201006"
save_freq: 5
device: "cuda"
epochs: 180
batch_size: 64
pretrained_model: ""
train_data: "ASRDataset/train_list.txt"
val_data: "ASRDataset/val_list.txt"

dataset_params:
  data_augmentation: false

preprocess_parasm:
  sr: 44100
  spect_params:
    n_fft: 4096
    win_length: 2400
    hop_length: 600
  mel_params:
    n_mels: 128

model_params:
   input_dim: 128
   hidden_dim: 256
   n_token: 178
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005